---
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
    bookdown::html_document2:
      number_sections: no
editor_options: 
  chunk_output_type: inline
---

## Overview

Across fifty-eight boreal caribou ranges in Canada, both survival and recruitment decrease with the percentage of the range that is disturbed ([Johnson et al. 2020](https://doi.org/10.1111/1365-2664.13637)). However, there is also variation in demographic rates among ranges, particularly where anthropogenic disturbance is low, and this variation leads to uncertainty in projections derived from national disturbance-demographic relationships ([Stewart et al. 2023](https://doi.org/10.1002/eap.2816); [Dyson et al. 2022](https://doi.org/10.1101/2022.06.01.494350)). Demographic projections derived from local range-specific data are also uncertain because few places have enough long-term monitoring data to characterize local demographic-disturbance relationships. We present a simple Bayesian population model that integrates prior information from national analysis of demographic-disturbance relationships with available local demographic data to reduce uncertainty in population viability projections. We combine this model with methods for simulating local population dynamics and monitoring to show how monitoring requirements depend on landscape condition. This interface is designed to allow exploration of user-specified monitoring and disturbance scenarios. See the [caribouMetrics](https://landscitech.github.io/caribouMetrics/) package and the [Bayesian Demographic Projection](https://landscitech.github.io/caribouMetrics/articles/BayesianDemographicProjection.html) vignette for more detailed descriptions of the models and methods. 

## Inputs

The model can be run with a simulated disturbance scenario and default values for all parameters by clicking **Run model**

### Scenario

The timeline for monitoring and projection, and change in anthropogenic disturbance over that period can be defined using either a csv file or several parameters that are used to generate a scenario. 

#### Scenario csv file

1. Choose the **Last year of observations**. Years before this will be included in the simulated observations and years after will be used for projections
2. Click **Select File** to select a csv file using a dialog box. The file must contain the columns "Year", "Anthro", and "fire_excl_anthro". The file must have one row per year that will be included in the observation and projection periods.
3. **Number of years of observation/projections** will appear after the file is loaded and can be used to reduce the number of years used for either period (described in detail below).

#### Simulate a scenario

1. Choose the **Last year of observations**. Years before this will be included in the simulated observations and years after will be used for projections
2. Choose a **Number of years of observations**. This value determines how much data the model will use in addition to the priors set from the national model. If it is low the projections will follow the national model. If it is higher and the observations are different from the national model the projections will be different from the national model. 
3. Choose a **Number of years of projections**. This is the number of years after the last observation that projections should be made for. 
4. Define the amount of anthropogenic disturbance in the scenario by selecting an **Initial % anthropogenic disturbance** and the **% increase in anthropogenic disturbance per year in observation/projection period**. The amount of disturbance caused by fire is assumed to be constant and can be set as the **Initial % natural disturbance**

### True population parameters

These parameters define the population that simulated observations will be sampled from relative to the national model. 

1. The **Initial population size** is the number of individuals at the start of the observations
2. The **Recruitment and Survival quantiles** determine the quantile of the distribution in the national model that the recruitment and survival coefficients are taken from. A quantile of 0.5 will give a population that follows the expected behaviour from the national model, while a quantile of 0.025 would follow the lower bound of the confidence interval from the national model. 
3. The **Multipliers for the effect of disturbance on recruitment/survival** are used to adjust the coefficients from the national model. Setting a value of 0 assumes that disturbance has no effect on recruitment/survival, while a value of 2 would double the effect of disturbance compared to the national model.


### Observation model parameters

These parameters define a local caribou population monitoring program that includes collaring of adult females and aerial recruitment surveys. Increasing the number of collars or the number of cows per collar in recruitment surveys increases the amount of local data available to inform local parameter estimates and demographic projections.

1. **Target number of collars**
2. **Number of years between collar deployments**
3. **Number of cows per collared cow in aerial surveys for calf:cow ratio each year**
2. **Number of years until collar falls off**
3. **Month that collars are deployed**. A number from 1 (January) to 12 (December)
4. **Month that collars fall off**. A number from 1 (January) to 12 (December)

### Model priors 

The first choice is which **version of the national model** to use. Johnson et al. 2020 includes 5 different recruitment and survival models the defaults are the best supported models but you can choose a different model number if desired. Note only models that use anthropogenic disturbance and/or fire excluding anthropogenic disturbance are supported at this time. Another option is to provide a csv file with custom coefficients where the column names are "responseVariable", "Coefficient", "Value", "lowerCI", and "upperCI". "responseVariable" must be one of "recruitment" or "femaleSurvival". And "Coefficient" must be one of "Intercept", "Anthro", "fire_excl_anthro" or "Precision". 

Higher values of the multiplier parameters in this section increase the vagueness of the priors for ceofficients in the demographic disturbance relationships. Default values are set so that the 95% prior prediction intervals for survival and recruitment from the Bayesian model match the
range between the 2.5% and 97.5% quantiles of 1000 simulated survival
and recruitment trajectories from the national demographic model. In other words, priors are set so the Bayesian population model and the national demographic model give comparable results when no local monitoring data is available to help refine parameter estimates.

1. **Multiplier for uncertainty about effect of disturbance on survival $\beta^S_a$**
2. **Multiplier for uncertainty about effect of disturbance on recruitment $\beta^R_a$**
3. **Multiplier for uncertainty about survival intercept $\beta^S_0$**
4. **Multiplier for uncertainty about recruitment intercept $\beta^R_0$**
5. **Interannual coefficient of variation for survival $\sigma^2_S$**
6. **Uncertainty about the interannual coefficient of variation for survival $\sigma^2_S$**
7. **Interannual coefficient of variation for recruitment $\sigma^2_R$**
8. **Uncertainty about the interannual coefficient of variation for recruitment $\sigma^2_R$**

### Baysian model parameters

These parameters can be adjusted to ensure convergence of the Markov Chain Monte Carlo estimation algorithm for the Bayesian population model.

1. **Number of chains**
2. **Number of iterations**
3. **Length of burn-in**
4. **Thinning rate**

## Outputs

Running the model can take some time. See the R console for details on the model progress. 

Once the model is finished the results graphs and tables tabs will be populated. You can also view the MCMC diagnostic plots in a new window by clicking **Open MCMC diagnostic plots**. This will also take some time with progress shown in the R console. 

Click **Save results to csv or rds** to save the outputs. The csv file will contain all the parameters used and the projected population metrics. If you save the results as a .rds file the whole model object will be saved and can be loaded into an R session using `readRDS()`




















